[platformio]
default_envs = firmware

[env:firmware]
platform = espressif32@6.7.0
framework = arduino
board = m5stick-c
board_build.flash_size = 8MB
monitor_speed = 115200
board_build.partitions = partitions.csv
build_flags =
  -DCORE_DEBUG_LEVEL=0
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
lib_deps =
  m5stack/M5Unified @ ^0.1.14
  bodmer/TJpg_Decoder @ ^1.1.0
