[platformio]
default_envs = m5stickc_plus2

[env:m5stickc_plus2]
platform = espressif32@6.9.0
board = m5stick-c
framework = arduino
lib_extra_dirs = ../_libs
; M5StickC Plus2 settings
board_build.partitions = no_ota.csv
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = dio
upload_speed = 1500000
monitor_speed = 115200

; Libraries
lib_deps =
lib_ignore =
    DFRobot_GP8XXX

; Increase stack size for emulation
build_unflags =
    -std=gnu++11
    -O2

build_flags =
    -std=gnu++17
    -O3
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DARDUINO_M5STICK_C_PLUS2
    -DCONFIG_SPIRAM_SUPPORT=1
    -DCONFIG_SPIRAM_USE_MALLOC=1
