[platformio]
default_envs = firmware

[env:firmware]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DDOOMGENERIC_RESX=320
    -DDOOMGENERIC_RESY=200
lib_deps = lovyan03/LovyanGFX
