[platformio]
default_envs = esp32s3_114tft

[env:esp32s3_114tft]
platform = espressif32@6.9.0
framework = arduino
board = 4d_systems_esp32s3_gen4_r8n16
monitor_speed = 115200
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
board_build.partitions = default_16MB.csv
build_flags =
  -DCORE_DEBUG_LEVEL=0
  -DUSER_SETUP_LOADED
  -DUSE_HSPI_PORT
  -DST7789_DRIVER
  -DTFT_WIDTH=172
  -DTFT_HEIGHT=320
  -DTFT_RGB_ORDER=TFT_BGR
  -DCGRAM_OFFSET
  -DTFT_MISO=-1
  -DTFT_MOSI=11
  -DTFT_SCLK=12
  -DTFT_CS=10
  -DTFT_DC=9
  -DTFT_RST=14
  -DTFT_BL=21
  -DTFT_BACKLIGHT_ON=1
  -DSPI_FREQUENCY=27000000
  -DSPI_READ_FREQUENCY=20000000
  -DLOAD_GLCD
lib_deps =
  bodmer/TFT_eSPI @ ^2.5.43
