[platformio]
default_envs = m5stickc_plus2

[env:m5stickc_plus2]
platform = espressif32@6.9.0
board = m5stick-c
framework = arduino
lib_extra_dirs = ../_libs
lib_deps =
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_flags = 
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -Os
lib_ignore = 
    DFRobot_GP8XXX
