[platformio]
default_envs = m5stickc_plus2

[env:m5stickc_plus2]
platform = espressif32@6.9.0
board = m5stick-c
framework = arduino
monitor_speed = 115200
upload_speed = 1500000

lib_deps =
  m5stack/M5Unified @ ^0.2.13
  ArduinoJson @ ^6.21.2

lib_extra_dirs =
  ../shared

build_flags =
  -DCORE_DEBUG_LEVEL=0
  -DARDUINO_USB_CDC_ON_BOOT=0
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
  -Isrc/nofrendo
  -Isrc/nofrendo/cpu
  -Isrc/nofrendo/nes
  -Isrc/nofrendo/libsnss
  -Isrc/nofrendo/mappers
  -Isrc/nofrendo/sndhrdw

board_build.partitions = huge_app.csv
board_upload.flash_size = 8MB
board_build.f_flash = 80000000L
board_build.flash_mode = dio
