[platformio]
default_envs = m5stickc_plus2

[env:m5stickc_plus2]
platform = espressif32@6.9.0
board = m5stick-c
framework = arduino
lib_extra_dirs = ../_libs
lib_deps =
    crankyoldgit/IRremoteESP8266@^2.8.6
monitor_speed = 115200
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
upload_speed = 1500000
build_flags = 
    -DCORE_DEBUG_LEVEL=0
    -DFAST_TETRIS_MODE=1
    -O3
    -DNDEBUG
    -ffast-math
    -funroll-loops
lib_ignore = 
    DFRobot_GP8XXX